SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DimAccount';


-- Top 10
SELECT TOP 10 * FROM DimAccount;


SELECT DISTINCT(AccountType) FROM DimAccount;

SELECT DISTINCT(AccountDescription) FROM DimAccount;

SELECT DISTINCT(ValueType) FROM DimAccount;

SELECT DISTINCT(CustomMemberOptions) FROM DimAccount;

SELECT DISTINCT(CustomMembers) FROM DimAccount;



