-- View Columns
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DimCustomer';


-- Top 10
SELECT TOP 10 * FROM dbo.DimCustomer;

-- Total Rows
SELECT DISTINCT CommuteDistance FROM DimCustomer;

SELECT DISTINCT EnglishEducation FROM DimCustomer;

SELECT DISTINCT EnglishOccupation FROM DimCustomer;