-- View Columns
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DimProduct';


-- Top 10
SELECT TOP 10 * FROM DimProduct;

-- Total Rows
SELECT DISTINCT Class FROM DimProduct;

SELECT DISTINCT Style FROM DimProduct;