-- View Columns
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DimSalesReason';

-- Top 10
SELECT TOP 10 * FROM DimSalesReason;

-- Total Rows
SELECT DISTINCT SalesReasonReasonType, SalesReasonName FROM DimSalesReason;