-- View Columns
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'FactProductInventory';

-- Top 10
SELECT TOP 10 * FROM dbo.FactProductInventory;

-- Total Rows
SELECT COUNT(*) AS TotalRows FROM FactProductInventory;